---
name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-latest"
    env:
      USING_COVERAGE: "3.7,3.8,3.9,3.10,pypy-3.8"

    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "pypy-3.8"]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: "Install dependencies"
        run: |
          set -xe
          python -VV
          python -m site
          python -m pip install --upgrade pip wheel poetry==1.2.0a2
          python -m pip install --upgrade coverage[toml] virtualenv tox tox-gh-actions
          poetry install 
      - name: "Run bench targets for ${{ matrix.python-version }}"
        run: "poetry run pytest bench --benchmark-warmup=on"


